name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: test
        run: |
            cd /usr/local
            sudo wget https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.08/riscv64-unknown-elf-gcc-10.1.0-2020.08.2-x86_64-linux-ubuntu14.tar.gz
            sudo tar xzf riscv64-unknown-elf-gcc-10.1.0-2020.08.2-x86_64-linux-ubuntu14.tar.gz
            sudo mv riscv64-unknown-elf-gcc-10.1.0-2020.08.2-x86_64-linux-ubuntu14 riscv64-unknown-elf-gcc
            sudo wget -O riscv64-linux-musl-cross.tgz https://cloud.tsinghua.edu.cn/f/b07bac9bcfa14f1dae66/?dl=1
            sudo tar xzf riscv64-linux-musl-cross.tgz
            sudo apt install -y cmake
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev \
                          gawk build-essential bison flex texinfo gperf libtool patchutils bc \
                          zlib1g-dev libexpat-dev pkg-config  libglib2.0-dev libpixman-1-dev git tmux python3
            cd $HOME
            sudo wget https://download.qemu.org/qemu-5.0.0.tar.xz
            sudo tar xJf qemu-5.0.0.tar.xz
            cd qemu-5.0.0
            sudo ./configure --target-list=riscv64-softmmu,riscv64-linux-user
            sudo make -j$(nproc)
            cd ../
            sudo touch .env
            sudo chmod 777 .env
            sudo echo "export PATH=\"/usr/local/riscv64-unknown-elf-gcc/bin:\$PATH\"" >> .env
            sudo echo "export PATH=\"/usr/local/riscv64-linux-musl-cross/bin:\$PATH\"" >> .env
            sudo echo "export PATH=\"$HOME/qemu-5.0.0:\$PATH\"" >> .env
            sudo echo "export PATH=\"$HOME/qemu-5.0.0/riscv64-softmmu:\$PATH\"" >> .env
            sudo echo "export PATH=\"$HOME/qemu-5.0.0/riscv64-linux-user:\$PATH\"" >> .env
            source $HOME/.bashrc
            qemu-system-riscv64 --version
            qemu-riscv64 --version
      - name: test
        run: |
            make run
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
